### PR TITLE
Add response to hello world

### PR DESCRIPTION
**Pull request by nick42072**
I have added a fucking response to your hello world. Aliens this side

### CODE REVIEW

**Comment by coderAkmal** [comment]
Mind your language

**Comment by nick42072** [comment]
please accept my pull request...warna andi mandi sandi

**Review by coderAkmal — CHANGES_REQUESTED** [review]
I have seen your commit. Looks interesting. Please add a more funny line :)

**Comment by nick42072** [comment]
i have added some text.please review.

**Pull request merged**
